"""create_permohonan_files_table

Revision ID: 058ca2bd18c1
Revises: f2eb518d6a89
Create Date: 2026-07-02 16:46:49.342574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '058ca2bd18c1'
down_revision: Union[str, Sequence[str], None] = 'f2eb518d6a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permohonan_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_key', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permohonan_files')
    # ### end Alembic commands ###
