"""drop_redundant_photo_columns_from_permohonan

Revision ID: 09cc0aaa2a7d
Revises: 058ca2bd18c1
Create Date: 2026-07-02 16:58:24.344107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '09cc0aaa2a7d'
down_revision: Union[str, Sequence[str], None] = '058ca2bd18c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan', 'photo_north')
    op.drop_column('permohonan', 'photo_south')
    op.drop_column('permohonan', 'photo_east')
    op.drop_column('permohonan', 'photo_access')
    op.drop_column('permohonan', 'photo_west')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permohonan', sa.Column('photo_west', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('photo_access', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('photo_east', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('photo_south', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('photo_north', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
