"""add_revisi_silsilah_columns

Revision ID: 38abd7df8602
Revises: 92210e5f9699
Create Date: 2026-07-14 12:38:46.273363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '38abd7df8602'
down_revision: Union[str, Sequence[str], None] = '92210e5f9699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('regency', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_references_district'), 'region_references', ['district'], unique=False)
    op.add_column('permohonan', sa.Column('parent_id_permohonan', sa.String(length=50), nullable=True))
    op.add_column('permohonan', sa.Column('replaced_sk_number', sa.String(length=100), nullable=True))
    op.add_column('permohonan', sa.Column('replaced_sk_date', sa.Date(), nullable=True))
    op.add_column('permohonan', sa.Column('replaced_sk_doc_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'permohonan', 'permohonan', ['parent_id_permohonan'], ['id_permohonan'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permohonan', type_='foreignkey')
    op.drop_column('permohonan', 'replaced_sk_doc_url')
    op.drop_column('permohonan', 'replaced_sk_date')
    op.drop_column('permohonan', 'replaced_sk_number')
    op.drop_column('permohonan', 'parent_id_permohonan')
    op.drop_index(op.f('ix_region_references_district'), table_name='region_references')
    op.drop_table('region_references')
    # ### end Alembic commands ###
