"""add_sk_draft_table_and_sk_number_column

Revision ID: 4a843b146644
Revises: 569881990be1
Create Date: 2026-07-09 16:31:57.193860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a843b146644'
down_revision: Union[str, Sequence[str], None] = '569881990be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sk_draft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sk', sa.String(length=50), nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('sk_number', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('document_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sk_draft_id_permohonan'), 'sk_draft', ['id_permohonan'], unique=False)
    op.create_index(op.f('ix_sk_draft_id_sk'), 'sk_draft', ['id_sk'], unique=True)
    op.create_index(op.f('ix_sk_draft_sk_number'), 'sk_draft', ['sk_number'], unique=True)
    op.add_column('permohonan', sa.Column('sk_number', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_permohonan_sk_number'), 'permohonan', ['sk_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permohonan_sk_number'), table_name='permohonan')
    op.drop_column('permohonan', 'sk_number')
    op.drop_index(op.f('ix_sk_draft_sk_number'), table_name='sk_draft')
    op.drop_index(op.f('ix_sk_draft_id_sk'), table_name='sk_draft')
    op.drop_index(op.f('ix_sk_draft_id_permohonan'), table_name='sk_draft')
    op.drop_table('sk_draft')
    # ### end Alembic commands ###
