"""add_telaah_staf_table_and_verifier_audit_columns

Revision ID: 569881990be1
Revises: 08830d8c7079
Create Date: 2026-07-09 10:33:12.668600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '569881990be1'
down_revision: Union[str, Sequence[str], None] = '08830d8c7079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telaah_staf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_telaah', sa.String(length=50), nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('document_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telaah_staf_id_permohonan'), 'telaah_staf', ['id_permohonan'], unique=False)
    op.create_index(op.f('ix_telaah_staf_id_telaah'), 'telaah_staf', ['id_telaah'], unique=True)
    op.drop_index(op.f('idx_bogor_lereng_geom'), table_name='bogor_lereng', postgresql_using='gist')
    op.drop_table('bogor_lereng')
    op.drop_index(op.f('idx_bogor_kebun_geom'), table_name='bogor_kebun', postgresql_using='gist')
    op.drop_table('bogor_kebun')
    op.drop_index(op.f('idx_bogor_relka_geom'), table_name='bogor_relka', postgresql_using='gist')
    op.drop_table('bogor_relka')
    op.drop_index(op.f('idx_bogor_sutet_geom'), table_name='bogor_sutet', postgresql_using='gist')
    op.drop_table('bogor_sutet')
    op.drop_index(op.f('idx_bogor_sawah_geom'), table_name='bogor_sawah', postgresql_using='gist')
    op.drop_table('bogor_sawah')
    op.drop_index(op.f('idx_bogor_pemukiman_geom'), table_name='bogor_pemukiman', postgresql_using='gist')
    op.drop_table('bogor_pemukiman')
    op.drop_index(op.f('idx_bogor_pasir_geom'), table_name='bogor_pasir', postgresql_using='gist')
    op.drop_table('bogor_pasir')
    op.drop_index(op.f('idx_bogor_sungai_geom'), table_name='bogor_sungai', postgresql_using='gist')
    op.drop_table('bogor_sungai')
    op.drop_index(op.f('idx_bogor_ladang_geom'), table_name='bogor_ladang', postgresql_using='gist')
    op.drop_table('bogor_ladang')
    op.add_column('evaluasi_checklist', sa.Column('verified_by_id', sa.Integer(), nullable=True))
    op.add_column('evaluasi_checklist', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'evaluasi_checklist', 'users', ['verified_by_id'], ['id'])
    op.add_column('permohonan', sa.Column('tech_water_source', sa.String(length=255), nullable=True))
    op.add_column('permohonan', sa.Column('kadis_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan', 'kadis_signature')
    op.drop_column('permohonan', 'tech_water_source')
    op.drop_constraint(None, 'evaluasi_checklist', type_='foreignkey')
    op.drop_column('evaluasi_checklist', 'verified_at')
    op.drop_column('evaluasi_checklist', 'verified_by_id')
    op.create_table('bogor_ladang',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_ladang_pkey'))
    )
    op.create_index(op.f('idx_bogor_ladang_geom'), 'bogor_ladang', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_sungai',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_sungai_pkey'))
    )
    op.create_index(op.f('idx_bogor_sungai_geom'), 'bogor_sungai', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_pasir',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_pasir_pkey'))
    )
    op.create_index(op.f('idx_bogor_pasir_geom'), 'bogor_pasir', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_pemukiman',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_pemukiman_pkey'))
    )
    op.create_index(op.f('idx_bogor_pemukiman_geom'), 'bogor_pemukiman', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_sawah',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_sawah_pkey'))
    )
    op.create_index(op.f('idx_bogor_sawah_geom'), 'bogor_sawah', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_sutet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_sutet_pkey'))
    )
    op.create_index(op.f('idx_bogor_sutet_geom'), 'bogor_sutet', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_relka',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_relka_pkey'))
    )
    op.create_index(op.f('idx_bogor_relka_geom'), 'bogor_relka', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_kebun',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_kebun_pkey'))
    )
    op.create_index(op.f('idx_bogor_kebun_geom'), 'bogor_kebun', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('bogor_lereng',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kelas', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('keterangan', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bogor_lereng_pkey'))
    )
    op.create_index(op.f('idx_bogor_lereng_geom'), 'bogor_lereng', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_telaah_staf_id_telaah'), table_name='telaah_staf')
    op.drop_index(op.f('ix_telaah_staf_id_permohonan'), table_name='telaah_staf')
    op.drop_table('telaah_staf')
    # ### end Alembic commands ###
