"""add_verified_raw_areas

Revision ID: 7e664cf3454c
Revises: bcf6bd28ef4c
Create Date: 2026-07-16 11:29:58.824631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '7e664cf3454c'
down_revision: Union[str, Sequence[str], None] = 'bcf6bd28ef4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('permohonan', sa.Column('verified_land_area', sa.Float(), nullable=True))
    op.add_column('permohonan', sa.Column('verified_building_area', sa.Float(), nullable=True))
    op.add_column('permohonan', sa.Column('verified_total_floor_area', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan', 'verified_total_floor_area')
    op.drop_column('permohonan', 'verified_building_area')
    op.drop_column('permohonan', 'verified_land_area')
    op.drop_table('system_feedbacks')
    # ### end Alembic commands ###
