"""add_verified_raw_areas

Revision ID: 7e664cf3454c
Revises: bcf6bd28ef4c
Create Date: 2026-07-16 11:29:58.824631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '7e664cf3454c'
down_revision: Union[str, Sequence[str], None] = 'bcf6bd28ef4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permohonan', sa.Column('verified_land_area', sa.Float(), nullable=True))
    op.add_column('permohonan', sa.Column('verified_building_area', sa.Float(), nullable=True))
    op.add_column('permohonan', sa.Column('verified_total_floor_area', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan', 'verified_total_floor_area')
    op.drop_column('permohonan', 'verified_building_area')
    op.drop_column('permohonan', 'verified_land_area')
    # ### end Alembic commands ###
