"""add baseline_source to permohonan

Revision ID: 8b9400381e3b
Revises: 38abd7df8602
Create Date: 2026-07-14 14:25:35.963290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '8b9400381e3b'
down_revision: Union[str, Sequence[str], None] = '38abd7df8602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permohonan', sa.Column('baseline_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan', 'baseline_source')
    # ### end Alembic commands ###
