"""separate_ground_and_aerial_inspection

Revision ID: 8c94bf630111
Revises: eb6e76f868d4
Create Date: 2026-07-20 09:55:20.468148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c94bf630111'
down_revision: Union[str, Sequence[str], None] = 'eb6e76f868d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_reference_layers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layer_key', sa.String(length=50), nullable=False),
    sa.Column('layer_name', sa.String(length=100), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_spatial_reference_layers_geom', 'spatial_reference_layers', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_reference_layers_layer_key'), 'spatial_reference_layers', ['layer_key'], unique=False)
    op.create_table('aerial_inspection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('pilot_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('drone_video_url', sa.String(length=500), nullable=False),
    sa.Column('flight_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aerial_inspection_logs_id_permohonan'), 'aerial_inspection_logs', ['id_permohonan'], unique=True)
    op.drop_column('field_inspection_logs', 'drone_video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_inspection_logs', sa.Column('drone_video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_aerial_inspection_logs_id_permohonan'), table_name='aerial_inspection_logs')
    op.drop_table('aerial_inspection_logs')
    op.drop_index(op.f('ix_spatial_reference_layers_layer_key'), table_name='spatial_reference_layers')
    # op.drop_index('idx_spatial_reference_layers_geom', table_name='spatial_reference_layers', postgresql_using='gist')
    op.drop_table('spatial_reference_layers')
    # ### end Alembic commands ###
