"""add tpu bukti_dokumen_url column

Revision ID: 92210e5f9699
Revises: d6627af55ed9
Create Date: 2026-07-10 10:27:30.724889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '92210e5f9699'
down_revision: Union[str, Sequence[str], None] = 'd6627af55ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permohonan_tpu', sa.Column('bukti_dokumen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan_tpu', 'bukti_dokumen_url')
    # ### end Alembic commands ###
