"""add_field_inspection_logs

Revision ID: b6994efb23ed
Revises: 10f86caaeae7
Create Date: 2026-07-16 14:19:12.490769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = 'b6994efb23ed'
down_revision: Union[str, Sequence[str], None] = '10f86caaeae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_inspection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('inspector_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('distance_from_boundary_meters', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_inspection_logs_id_permohonan'), 'field_inspection_logs', ['id_permohonan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_inspection_logs_id_permohonan'), table_name='field_inspection_logs')
    op.drop_table('field_inspection_logs')
    # ### end Alembic commands ###
