"""refactor_silsilah_lineage

Revision ID: bcf6bd28ef4c
Revises: add_unique_active_pejabat_idx
Create Date: 2026-07-15 16:29:35.878760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = 'bcf6bd28ef4c'
down_revision: Union[str, Sequence[str], None] = 'add_unique_active_pejabat_idx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('silsilah_permohonan',
    sa.Column('id_silsilah', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=False),
    sa.Column('baseline_source', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('legacy_sk_number', sa.String(length=100), nullable=True),
    sa.Column('legacy_sk_date', sa.Date(), nullable=True),
    sa.Column('legacy_sk_doc_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['permohonan.id_permohonan'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_silsilah')
    )
    op.drop_index(op.f('ix_region_references_district'), table_name='region_references')
    op.drop_table('region_references')
    op.add_column('permohonan', sa.Column('admin_lock_id', sa.Integer(), nullable=True))
    op.add_column('permohonan', sa.Column('teknisi_lock_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('permohonan_parent_id_permohonan_fkey'), 'permohonan', type_='foreignkey')
    op.create_foreign_key(None, 'permohonan', 'users', ['admin_lock_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'permohonan', 'users', ['teknisi_lock_id'], ['id'], ondelete='SET NULL')
    op.drop_column('permohonan', 'replaced_sk_date')
    op.drop_column('permohonan', 'replaced_sk_number')
    op.drop_column('permohonan', 'replaced_sk_doc_url')
    op.drop_column('permohonan', 'parent_id_permohonan')
    op.drop_index(op.f('idx_unique_active_pejabat'), table_name='users', postgresql_where="((is_active = true) AND ((role)::text = ANY ((ARRAY['KADIS'::character varying, 'KABID_PUPR'::character varying])::text[])))")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_unique_active_pejabat'), 'users', ['role'], unique=True, postgresql_where="((is_active = true) AND ((role)::text = ANY ((ARRAY['KADIS'::character varying, 'KABID_PUPR'::character varying])::text[])))")
    op.add_column('permohonan', sa.Column('parent_id_permohonan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('replaced_sk_doc_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('replaced_sk_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('permohonan', sa.Column('replaced_sk_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'permohonan', type_='foreignkey')
    op.drop_constraint(None, 'permohonan', type_='foreignkey')
    op.create_foreign_key(op.f('permohonan_parent_id_permohonan_fkey'), 'permohonan', 'permohonan', ['parent_id_permohonan'], ['id_permohonan'], ondelete='SET NULL')
    op.drop_column('permohonan', 'teknisi_lock_id')
    op.drop_column('permohonan', 'admin_lock_id')
    op.create_table('region_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('regency', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('village', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('region_references_pkey'))
    )
    op.create_index(op.f('ix_region_references_district'), 'region_references', ['district'], unique=False)
    op.drop_table('silsilah_permohonan')
    op.drop_table('system_feedbacks')
    # ### end Alembic commands ###
