"""Add site plan geometry table

Revision ID: d204ef962454
Revises: e917621d0d21
Create Date: 2026-06-29 13:52:43.085017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = 'd204ef962454'
down_revision: Union[str, Sequence[str], None] = 'e917621d0d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_plan_geometries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('layer_name', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_plan_geometries_geom', 'site_plan_geometries', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_site_plan_geometries_geom', table_name='site_plan_geometries', postgresql_using='gist')
    op.drop_table('site_plan_geometries')
    # ### end Alembic commands ###
