"""add_permohonan_tpu_table

Revision ID: d6627af55ed9
Revises: 4a843b146644
Create Date: 2026-07-10 10:09:19.195203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = 'd6627af55ed9'
down_revision: Union[str, Sequence[str], None] = '4a843b146644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permohonan_tpu',
    sa.Column('id_tpu', sa.String(length=50), nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('metode', sa.String(length=50), nullable=False),
    sa.Column('luas', sa.Float(), nullable=True),
    sa.Column('nama_tpu', sa.String(length=255), nullable=True),
    sa.Column('pengurus_tpu', sa.String(length=255), nullable=True),
    sa.Column('no_pks', sa.String(length=255), nullable=True),
    sa.Column('nominal_kompensasi', sa.Float(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('status_verifikasi', sa.String(length=50), nullable=False),
    sa.Column('catatan_verifikasi', sa.Text(), nullable=True),
    sa.Column('diverifikasi_oleh', sa.String(length=255), nullable=True),
    sa.Column('diverifikasi_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_tpu'),
    sa.UniqueConstraint('id_permohonan')
    )
    op.create_index(op.f('ix_permohonan_tpu_id_tpu'), 'permohonan_tpu', ['id_tpu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permohonan_tpu_id_tpu'), table_name='permohonan_tpu')
    op.drop_table('permohonan_tpu')
    # ### end Alembic commands ###
