"""Create spatial siteplan schemas

Revision ID: e917621d0d21
Revises: 6e00ff0099cc
Create Date: 2026-06-29 13:37:03.400136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e917621d0d21'
down_revision: Union[str, Sequence[str], None] = '6e00ff0099cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=50), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status_before', sa.String(length=50), nullable=False),
    sa.Column('status_after', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_submission_id'), 'audit_trail', ['submission_id'], unique=False)
    op.create_table('permohonan',
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('submission_no', sa.String(length=100), nullable=False),
    sa.Column('housing_name', sa.String(length=255), nullable=False),
    sa.Column('developer_name', sa.String(length=255), nullable=False),
    sa.Column('land_area', sa.Float(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('buffer_sla', sa.Integer(), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_permohonan')
    )
    op.create_index(op.f('ix_permohonan_id_permohonan'), 'permohonan', ['id_permohonan'], unique=False)
    op.create_index(op.f('ix_permohonan_submission_no'), 'permohonan', ['submission_no'], unique=True)
    op.create_table('lahan_kompensasi',
    sa.Column('id_kompensasi', sa.String(length=50), nullable=False),
    sa.Column('id_permohonan', sa.String(length=50), nullable=False),
    sa.Column('tipe_kompensasi', sa.String(length=50), nullable=False),
    sa.Column('luas_kompensasi_m2', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status_pemenuhan', sa.String(length=50), nullable=False),
    sa.Column('nilai_nominal', sa.Float(), nullable=False),
    sa.Column('bukti_legalitas_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_permohonan'], ['permohonan.id_permohonan'], ),
    sa.PrimaryKeyConstraint('id_kompensasi')
    )
    # op.create_index('idx_lahan_kompensasi_geom', 'lahan_kompensasi', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_lahan_kompensasi_id_kompensasi'), 'lahan_kompensasi', ['id_kompensasi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lahan_kompensasi_id_kompensasi'), table_name='lahan_kompensasi')
    # op.drop_index('idx_lahan_kompensasi_geom', table_name='lahan_kompensasi', postgresql_using='gist')
    op.drop_table('lahan_kompensasi')
    op.drop_index(op.f('ix_permohonan_submission_no'), table_name='permohonan')
    op.drop_index(op.f('ix_permohonan_id_permohonan'), table_name='permohonan')
    op.drop_table('permohonan')
    op.drop_index(op.f('ix_audit_trail_submission_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
