"""add_sla_start_date_to_permohonan

Revision ID: f8bb20134042
Revises: 09cc0aaa2a7d
Create Date: 2026-07-06 11:41:12.112082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = 'f8bb20134042'
down_revision: Union[str, Sequence[str], None] = '09cc0aaa2a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permohonan', sa.Column('sla_start_date', sa.Date(), nullable=True))
    op.execute("UPDATE permohonan SET sla_start_date = submission_date")
    op.alter_column('permohonan', 'sla_start_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permohonan', 'sla_start_date')
    # ### end Alembic commands ###
