version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geosipas_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sipas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sipas_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: geosipas_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  geoserver:
    image: kartoza/geoserver:2.24.1
    container_name: geosipas_geoserver
    restart: always
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    depends_on:
      - db

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: geosipas_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/sipas_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GEOSERVER_URL=http://geoserver:8080/geoserver
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=geoserver
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: geosipas_celery_worker
    restart: always
    command: celery -A src.infrastructure.queue.celery_app:celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/sipas_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GEOSERVER_URL=http://geoserver:8080/geoserver
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=geoserver
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  geoserver_data:
